INSERT INTO products (type, name, img)
VALUES
('News', 'Fresh Royal Cheeseburger', 'https://mcdonalds.ge/0e03542cf306-resized.png'),
('News', 'BBQ Royal Cheeseburger', 'https://mcdonalds.ge/cd093fe31877.Royal-resized.png'),
('News', 'Double BBQ Bacon Royal Cheeseburger', 'https://mcdonalds.ge/21760dd15339-resized.png'),
('News', 'Oreo Donut', 'https://mcdonalds.ge/b545b053a3f3-resized.png'),
('News', 'Sharing Box', 'https://mcdonalds.ge/036a68d84cd8-resized.png'),
('News', 'Double Fillet-O-Fish', 'https://mcdonalds.ge/fc3bf44b0604-resized.png'),
('News', 'Double Veggie Burger', 'https://mcdonalds.ge/15684610b692-resized.png'),
('News', 'Fishmac (fasting)', 'https://mcdonalds.ge/a595447177a4-resized.png'),
('News', 'Veggie Burger', 'https://mcdonalds.ge/e813e16a05fe-resized.png'),
('News', 'Veggie Roll', 'https://mcdonalds.ge/16e800db68f9-resized.png'),
('Sandwiches', 'Toast with Bacon', 'https://mcdonalds.ge/b9934c9b6e56-resized-resized.png'),
('Sandwiches', 'Hamburger', 'https://mcdonalds.ge/f91b2aa18a00-resized-resized.png'),
('Sandwiches', 'Cheeseburger', 'https://mcdonalds.ge/c44b58b83bc2-resized-resized.png'),
('Sandwiches', 'McToast', 'https://mcdonalds.ge/c7d14ea17c4e-resized-resized.png'),
('Sandwiches', 'Big Tasty', 'https://mcdonalds.ge/c82755417e61-resized-resized.png'),
('Sandwiches', 'Double Cheeseburger', 'https://mcdonalds.ge/a08c47be3bd6-resized-resized.png'),
('Sandwiches', 'McChicken', 'https://mcdonalds.ge/01212dc34ff8-resized-resized.png'),
('Sandwiches', 'Big Mac', 'https://mcdonalds.ge/7dfd49e1d85f-resized-resized.png'),
('Sandwiches', 'Royal Cheeseburger', 'https://mcdonalds.ge/bb09989baf72-resized-resized.png'),
('Sandwiches', 'Mini Chicken', 'https://mcdonalds.ge/c9247e4399b4-resized-resized.png'),
('Sandwiches', 'McFresh', 'https://mcdonalds.ge/61fb6640a557-resized-resized.png'),
('Sandwiches', 'Double McFresh', 'https://mcdonalds.ge/1480d991a1b5-resized-resized.png'),
('Sandwiches', 'Double Chilli Cheeseburger', 'https://mcdonalds.ge/da0267c13485-resized-resized.png'),
('Sandwiches', 'Double Chicken Cheeseburger', 'https://mcdonalds.ge/868f7d6fbfa3-resized-resized.png'),
('Sandwiches', 'Triple Cheeseburger', 'https://mcdonalds.ge/8f418b55fa0f-resized-resized.png'),
('Sandwiches', 'Triple Chilli Cheeseburger', 'https://mcdonalds.ge/d361c5cc14e1-resized-resized.png'),
('Rolls & Salads', 'Fish Roll (fasting)', 'https://mcdonalds.ge/0cddee43d9da-resized-resized.png'),
('Rolls & Salads', 'Veggie Roll', 'https://mcdonalds.ge/486a8944b4ed-resized-resized.png'),
('Rolls & Salads', 'Chicken Roll', 'https://mcdonalds.ge/f752f17ec039-resized-resized.png'),
('Rolls & Salads', 'Vegetable Salad', 'https://mcdonalds.ge/cacff4eca3bd-resized-resized.png'),
('Rolls & Salads', 'Caesar Salad', 'https://mcdonalds.ge/77a4dceb88cf-resized-resized.png'),
('Fries & Starters', 'Chicken McNuggets 6pcs', 'https://mcdonalds.ge/e6741386bab0-resized-resized.png'),
('Fries & Starters', 'Chicken McNuggets 9pcs', 'https://mcdonalds.ge/96d42909af64-resized-resized.png'),
('Fries & Starters', 'Chicken McNuggets 20pcs', 'https://mcdonalds.ge/23ae553a886d-resized-resized.png'),
('Fries & Starters', 'Spicy Chicken McNuggets 4pcs', 'https://mcdonalds.ge/8645b24f4fa1-resized-resized.png'),
('Fries & Starters', 'Spicy Chicken McNuggets 6pcs', 'https://mcdonalds.ge/94b6026fcd42-resized-resized.png'),
('Fries & Starters', 'Spicy Chicken McNuggets 9pcs', 'https://mcdonalds.ge/2aa93dfd302d-resized-resized.png'),
('Fries & Starters', 'Spicy Chicken McNuggets 20pcs', 'https://mcdonalds.ge/022a3b043b1e-resized-resized.png'),
('Fries & Starters', 'Chicken Wings 4pcs', 'https://mcdonalds.ge/c40936541d17-resized-resized.png'),
('Fries & Starters', 'Chicken Wings 2pcs', 'https://mcdonalds.ge/5331b7f49bb9-resized-resized.png'),
('Fries & Starters', 'Potato Filet', 'https://mcdonalds.ge/9d32cf2319f6-resized-resized.png'),
('Fries & Starters', 'Kids Size Fries', 'https://mcdonalds.ge/f8fa79a0fa25-resized-resized.png'),
('Fries & Starters', 'Medium Size Fries', 'https://mcdonalds.ge/beeed646f451-resized-resized.png'),
('Fries & Starters', 'Standard Size Fries', 'https://mcdonalds.ge/dd5a508efaf7-resized-resized.png'),
('Fries & Starters', 'Fries with Jalapeno', 'https://mcdonalds.ge/da1c1d6a351e-resized-resized.png'),
('Sauces', 'Bittersweet Sauce', 'https://mcdonalds.ge/c93189d085a1-resized-resized.png'),
('Sauces', 'BBQ Sauce', 'https://mcdonalds.ge/b4e6062a042d-resized-resized.png'),
('Sauces', 'Mustard', 'https://mcdonalds.ge/91be61ac9d4f-resized-resized.png'),
('Sauces', 'Cheese Sauce', 'https://mcdonalds.ge/b8b429c876c2-resized-resized.png'),
('Sauces', 'Ketchup', 'https://mcdonalds.ge/faaa4671627b-resized-resized.png'),
('Sauces', 'Mayonnaise', 'https://mcdonalds.ge/19d61c624e93-resized-resized.png'),
('Sauces', 'Caesar Dressing', 'https://mcdonalds.ge/c06e07801bd1-resized-resized.png'),
('McCafe Drinks', 'Black Tea', 'https://mcdonalds.ge/59c72460a8b7-resized-resized.png'),
('McCafe Drinks', 'Green Tea', 'https://mcdonalds.ge/7c8f6cb0f43a-resized-resized.png'),
('McCafe Drinks', 'Fruit Tea', 'https://mcdonalds.ge/a2aba8c3fdc8-resized-resized.png'),
('McCafe Drinks', 'Mint Tea', 'https://mcdonalds.ge/905b18ad84e4-resized-resized.png'),
('McCafe Drinks', 'Iced Americano', 'https://mcdonalds.ge/d9132af8a9b7-resized-resized.png'),
('McCafe Drinks', 'Iced Latte', 'https://mcdonalds.ge/3f36cc05973c-resized-resized.png'),
('McCafe Drinks', 'Iced Latte with Cream', 'https://mcdonalds.ge/a623fb6d0687-resized-resized.png'),
('McCafe Drinks', 'Iced Americano with Ice Cream', 'https://mcdonalds.ge/fb55f9d930e2-resized-resized.png'),
('McCafe Drinks', 'Iced Coffee', 'https://mcdonalds.ge/0739d4ff6192-resized-resized.png'),
('McCafe Drinks', 'Americano Small', 'https://mcdonalds.ge/908c94712204-resized-resized.png'),
('McCafe Drinks', 'Americano Classic', 'https://mcdonalds.ge/9aafb6f49928-resized-resized.png'),
('McCafe Drinks', 'Cappuccino Small', 'https://mcdonalds.ge/da8a2c6293e4-resized-resized.png'),
('McCafe Drinks', 'Cappuccino Classic', 'https://mcdonalds.ge/7fb1ea3a4a33-resized-resized.png'),
('McCafe Drinks', 'Latte Small', 'https://mcdonalds.ge/37c27fe05489-resized-resized.png'),
('McCafe Drinks', 'Latte Classic', 'https://mcdonalds.ge/09f268326f4d-resized-resized.png'),
('McCafe Drinks', 'Espresso', 'https://mcdonalds.ge/78402accf445-resized-resized.png'),
('McCafe Drinks', 'Double Espresso', 'https://mcdonalds.ge/51abf8d38e5d-resized-resized.png'),
('McCafe Drinks', 'Flat White', 'https://mcdonalds.ge/3c6047db434b-resized-resized.png'),
('Cold Drinks', 'Kids Size Coca-Cola Zero Sugar', 'https://mcdonalds.ge/f729db16b5e7-resized-resized.png'),
('Cold Drinks', 'Medium Coca-Cola Zero Sugar', 'https://mcdonalds.ge/57662b1ae380-resized-resized.png'),
('Cold Drinks', 'Standard Coca-Cola Zero Sugar', 'https://mcdonalds.ge/e57bf8c434bf-resized-resized.png'),
('Cold Drinks', 'Kids Size Coca-Cola', 'https://mcdonalds.ge/eba8a12edefd-resized-resized.png'),
('Cold Drinks', 'Medium Size Coca-Cola', 'https://mcdonalds.ge/7b0ebf50d22b-resized-resized.png'),
('Cold Drinks', 'Standard Size Coca-Cola', 'https://mcdonalds.ge/6794d3b3cabc-resized-resized.png'),
('Cold Drinks', 'Kids Size Fanta', 'https://mcdonalds.ge/8fef70464530-resized-resized.png'),
('Cold Drinks', 'Medium Size Fanta', 'https://mcdonalds.ge/f833a0071e17-resized-resized.png'),
('Cold Drinks', 'Standard Size Fanta', 'https://mcdonalds.ge/bbb6a9504d23-resized-resized.png'),
('Cold Drinks', 'Kids Size Sprite', 'https://mcdonalds.ge/b389c8484ba9-resized-resized.png'),
('Cold Drinks', 'Medium Size Sprite', 'https://mcdonalds.ge/3064abf319d8-resized-resized.png'),
('Cold Drinks', 'Standard Size Sprite', 'https://mcdonalds.ge/ce5f653d2434-resized-resized.png'),
('Cold Drinks', 'Medium Size Orange Juice', 'https://mcdonalds.ge/0ac240ca7d66-resized-resized.png'),
('Cold Drinks', 'Standard Size Orange Juice', 'https://mcdonalds.ge/1cc74e554dbc-resized-resized.png'),
('Cold Drinks', 'Bonaqua', 'https://mcdonalds.ge/1faad375d533-resized-resized.png'),
('Cold Drinks', 'Cherry Lemonade', 'https://mcdonalds.ge/cc018bde547f-resized-resized.png'),
('Cold Drinks', 'Watermelon Lemonade', 'https://mcdonalds.ge/0bfb3f595672-resized-resized.png'),
('Cold Drinks', 'Apple and Pear Bio Juice', 'https://mcdonalds.ge/f8f9749cb17b-resized-resized.png'),
('Cold Drinks', 'Iced Coffee', 'https://mcdonalds.ge/0739d4ff6192-resized-resized.png'),
('Desserts', 'Donut with Chocolate', 'https://mcdonalds.ge/c715d64cefc9-resized-resized.png'),
('Desserts', 'Chocolate Muffin', 'https://mcdonalds.ge/ee38122a6bc3-resized-resized.png'),
('Desserts', 'Cherry Pie', 'https://mcdonalds.ge/5ed06a01d913-resized-resized.png'),
('Desserts', 'Fruit Puree', 'https://mcdonalds.ge/355f9728d4ef-resized-resized.png'),
('Desserts', 'Oreo Donut', 'https://mcdonalds.ge/b541b8a90557-resized-resized.png'),
('Happy Meal', 'Happy Meal with 4pcs Chicken Nuggets', 'https://mcdonalds.ge/86454fd1a4db-resized-resized.png'),
('Happy Meal', 'Happy Meal with Hamburger', 'https://mcdonalds.ge/add819b2b523-resized-resized.png'),
('Happy Meal', 'Happy Meal with Cheeseburger', 'https://mcdonalds.ge/3a047c095c26-resized-resized.png'),
('Happy Meal', 'Happy Meal with McToast', 'https://mcdonalds.ge/a6cd3a446f06-resized-resized.png'),
('Happy Meal', 'Happy Meal with Mini Chicken', 'https://mcdonalds.ge/9f43a864d99d-resized-resized.png'),
('McMenu', 'Double Egg Muffin with Beef', ''),
('McMenu', 'Double Omelette Muffin with Beef', ''),
('McMenu', 'Fresh Omelette Muffin', ''),
('McMenu', 'Fresh Eff Muffin', ''),
('McCafe Desserts', 'Raspberry Cake', 'https://mcdonalds.ge/b79b96636a53-resized-resized.png'),
('McCafe Desserts', 'Strawberry Cake', 'https://mcdonalds.ge/13a53d5d11b9-resized-resized.png'),
('McCafe Desserts', 'Chocolate Tart', 'https://mcdonalds.ge/a2c660806726-resized-resized.png'),
('McCafe Desserts', 'Peanut Cake', 'https://mcdonalds.ge/48842e2729b4-resized-resized.png'),
('McCafe Desserts', 'Oreo Donut', 'https://mcdonalds.ge/b541b8a90557-resized-resized.png'),
('McCafe Desserts', 'Classic Cheesecake', 'https://mcdonalds.ge/187db452b9ef-resized-resized.png'),
('McCafe Desserts', 'Cheesecake with Chocolate Topping', 'https://mcdonalds.ge/12fc8df0ac32-resized-resized.png'),
('McCafe Desserts', 'Cheesecake with Strawberry Topping', 'https://mcdonalds.ge/2b02452bc5b5-resized-resized.png'),
('McCafe Desserts', 'Cheesecake with Caramel Topping', 'https://mcdonalds.ge/58c8eced1bb0-resized-resized.png'),
('McCafe Desserts', 'Brownie', 'https://mcdonalds.ge/ac7dfc8ef111-resized-resized.png'),
('McCafe Desserts', 'Brownie with Ice Cream', 'https://mcdonalds.ge/976bd5d4b60e-resized-resized.png'),
('McCafe Desserts', 'Tiramisu', 'https://mcdonalds.ge/ed054e17c7c4-resized-resized.png'),
('McCafe Desserts', 'Classic Croissant', 'https://mcdonalds.ge/d9a256dbfbc5-resized-resized.png'),
('McCafe Desserts', 'Pain Au Chocolate', 'https://mcdonalds.ge/56ef28db8ead-resized-resized.png'),
('McCafe Desserts', 'Chocolate Muffin', 'https://mcdonalds.ge/48735a93998f-resized-resized.png'),
('McCafe Desserts', 'Chocolate Donut', 'https://mcdonalds.ge/fb7b907236b1-resized-resized.png');




