INSERT INTO charity (year, image, description)
VALUES
(2024, 'https://mcdonalds.ge/57de53cd27f2-resized.jpg', 'This year’s beneficiary of the campaign is the Autism Center "Pyramid" in Tbilisi. The aim of this campaign is to improve the environment for children with special needs and create new opportunities for them.'),
(2024, 'https://mcdonalds.ge/b5cb51a0c643-resized.jpg', '"Extend a Helping Hand" – McDonald''s Georgia Launches McHappy Day Charity Campaign. At McDonald''s Georgia, we celebrate International Children''s Day with special enthusiasm every year. This year, we hosted children from the "Pyramid" Autism Center in Tbilisi, brightening their day with Happy Meals, colorful balloons, and fun activities.'),
(2022, 'https://mcdonalds.ge/43e3c932cbba-resized.jfif', ' "McDonald''s Georgia" donated an amount of 30,000 GEL to the "First Step" organization that takes care of children with special needs, in order to provide for various needs and improve the existing conditions for children.'),
(2021, 'https://mcdonalds.ge/bfb3b66728ba-resized.jpg', 'The campaign, which ran from April 15 to June 1 this year, brought McDonald''s and consumers together for a common purpose - to help blind and partially sighted children and to promote their full education.'),
(2019, 'https://mcdonalds.ge/ebe796fbaee5-resized.png', 'On June 1, McDonald''s annual charity event McHappy Day began. During the campaign, McDonald''s will assist the association “Georgian SOS Children''s Village”-s Zugdidi branch.'),
(2018, 'https://mcdonalds.ge//assets/seed/happydays-1.png', 'In 2018, McDonald''s helped children with disabilities of the Kutaisi’s day center "Magic Morld" within the annual charity event Mc Happy Day. The proceeds were donated to a non-governmental organization - Center for Education Development and Employment (EDEC), which provided the purchase of an adapted minivan for children.'),
(2017, 'https://mcdonalds.ge//assets/seed/happydays-2.png', 'In 2017, McDonald''s, within the annual Mc Happy Day charity event, helped the Kutaisi-based non-governmental organization "Bridge for Social Inclusion" to provide a sensory room in the Kutaisi Day Center.'),
(2016, 'https://mcdonalds.ge//assets/seed/happydays-3.png', 'In 2016, McDonald''s was partnered with children of typical and atypical development living in 5 different cities of Georgia in Batumi, Zugdidi, Kutaisi, Rustavi and Tbilisi. '),
(2015, 'https://mcdonalds.ge//assets/seed/happydays-4.png', 'In 2015, as part of the "Closer, Easier" charity event organized by McDonald''s, 20,000 GEL was transferred to the children of the social enterprise "Kedeli" and the "Kojori Orphanage for Children with Disabilities".'),
(2014, 'https://mcdonalds.ge/face6c0b9eea-resized.png', 'On November 18, a press conference was held at the McDonald''s charity event "Send Emotion". As part of the campaign, McDonald''s donated 10,000 GEL to the Dimitri Tsintsadze Foundation.');
